{% set name = "dwave-greedy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-greedy-{{ version }}.tar.gz
  sha256: 58b0bea15b72aa9e390084f6be0c69b7bbc7a959b98eecf75887062b8c03b053

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.24,<3.0
    - numpy >=1.17.3,<2.0.0
    - setuptools >=46.4.0
    - wheel >=0.30.0
    - pip
    - python
  run:
    - dimod >=0.9.2,<0.13.0
    - importlib-metadata >=1.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - greedy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-greedy
  summary: Ocean-compatible collection of greedy/brute-force solvers/samplers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
